# Generated by Django 4.2.3 on 2023-07-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='first_name',
            new_name='name',
        ),
    ]
