# Generated by Django 4.2.3 on 2023-07-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_first_name_login_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='name1',
        ),
    ]
