# Generated by Django 4.2.3 on 2023-07-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_login_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name1',
            new_name='name',
        ),
    ]
